#!/usr/bin/python

import unixpipe
from gandi.cli.core.base import UsageError
from gandi.cli.modules.iaas import Iaas

import socket
import subprocess
import sys

if __name__ == '__main__':
    try:
        docker = Iaas.info('docker')
    except UsageError:
        print 'Sorry to bother you, exit the shell when docker is ready'
        Iaas.create('LU', 512, 1, 4, 100*1024, None, None,
            'docker', 'Ubuntu 14.04 64 bits LTS',
            'wget -O - https://get.docker.io/ | sh', False,
            Iaas.get('sshkey'))
        docker = Iaas.info('docker')

    if docker['state'] != 'running':
        Iaas.start('docker')
        # Do not sleep or ping - Iaas.start should do it well (?)

    remote_addr = None
    for iface in docker['ifaces']:
        for ip in iface['ips']:
            if ip['version'] == 4:
                remote_addr = ip['ip']

    #XXX key
    unixpipe.setup(remote_addr, 'root', '/var/run/docker.sock')

    subprocess.call(['docker', '-H', 
        'tcp://localhost:%d' % unixpipe.service_port()] + sys.argv[1:])
